import { useState, type FormEvent } from "react";

import type { ApiSession } from "../types";

interface Props {
  busy: boolean;
  error: string | null;
  onConnect: (session: ApiSession) => Promise<void>;
}

export function AuthSetup({ busy, error, onConnect }: Props) {
  const [token, setToken] = useState("");
  const [productId, setProductId] = useState("");
  const [tenantId, setTenantId] = useState("");

  async function submit(event: FormEvent) {
    event.preventDefault();
    await onConnect({ token: token.trim(), productId: productId.trim(), tenantId: tenantId.trim() });
  }

  return (
    <section className="panel" aria-labelledby="connection-title">
      <div className="section-heading">
        <div>
          <p className="step">Demo connection</p>
          <h2 id="connection-title">Connect to an authorized scope</h2>
        </div>
        <span className="badge badge--neutral">Local demo</span>
      </div>
      <p className="help">Paste the short-lived demo values generated by the documented setup command.</p>
      <form className="form-grid" onSubmit={(event) => void submit(event)}>
        <label className="field field--wide">
          <span>Bearer token</span>
          <input
            aria-label="Bearer token"
            autoComplete="off"
            onChange={(event) => setToken(event.target.value)}
            required
            type="password"
            value={token}
          />
        </label>
        <label className="field">
          <span>Product ID</span>
          <input onChange={(event) => setProductId(event.target.value)} required value={productId} />
        </label>
        <label className="field">
          <span>Tenant ID</span>
          <input onChange={(event) => setTenantId(event.target.value)} required value={tenantId} />
        </label>
        <button className="button" disabled={busy} type="submit">
          {busy ? "Connecting…" : "Connect"}
        </button>
      </form>
      {error && <div className="message message--error" role="alert">{error}</div>}
    </section>
  );
}
